name: fetch

on:
  push:
    branches:
      - main
    paths:
      - "packages/fetch/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/fetch/**"
      - ".github/workflows/fetch.yml"

jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
        project:
          - fetch
    steps:
      - uses: actions/checkout@v3

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: packages/${{matrix.project}}/tsconfig.json

  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 16
          - 18
          - 20
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - fetch
        exclude:
          - os: windows-latest
            node-version: 14
          # On macOS, run tests with only the LTS environments.
          - os: macos-latest
            node-version: 14

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Test (ESM)
        run: yarn --cwd packages/${{matrix.project}} test -- --colors

      # upload coverage only once
      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == '14' && matrix.os == 'ubuntu-latest'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test (CJS)
        run: yarn --cwd packages/${{matrix.project}} test:cjs
