name: form-data

on:
  push:
    branches:
      - main
    paths:
      - "packages/form-data/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/form-data/**"
      - ".github/workflows/form-data.yml"

jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
        project:
          - form-data
    steps:
      - uses: actions/checkout@v3

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: packages/${{matrix.project}}/tsconfig.json
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 14
          - 16
          - 18
          - 20
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - form-data

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test (ES)
        run: yarn --cwd packages/${{matrix.project}} test:es

      - name: Test (CJS)
        run: yarn --cwd packages/${{matrix.project}} test:cjs

      - name: Test (Web)
        run: yarn --cwd packages/${{matrix.project}} test:web
